name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      HEADLESS: true

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
	  node-version: 12.x

      - name: Install Node.js dependencies
        run: npm install

      - name: Lint Code
        run: $(npm bin)/grunt lint

      - name: Node Tests
        run: npm test
